---
# If present, show a table with column headers in item lists
itemList:
  # layout does not need to be specified.
  layout:
    # The default list (with flatten: false) shows only the items in the
    # current folder; flattening the list shows items in the current folder
    # and all subfolders.  This can also be "only", in which case the
    # flatten option will start enabled and, when flattened, the folder
    # list will be hidden.
    flatten: true
    # The default layout is a list.  This can optionally be "grid"
    # mode: grid
    # max-width is only used in grid mode.  It is the maximum width in
    # pixels for grid entries.  It defaults to 250.
    max-width: 250
  # group does not need to be specified.  Instead of listing items
  # directly, multiple items can be grouped  together.
  #group:
    # keys is a single metadata value reference (see the column metadata
    # records), or a list of such records.
    # keys: dicom.PatientID
    # counts is optional.  If specified, the left side is either a metadata
    # value references or "_id" to just count total items.  The right side
    # is where, conceptually, the count is stored in the item.meta record.
    # to show a column of the counts, add a metadata column with a value
    # equal to this.  That is, in this example, all items with the same
    # meta.dicom.PatientID are grouped as a single row, and two count
    # columns are generated.  The unique values for each group row of
    # meta.dicom.StudyInstanceUID and counted and that count is added to
    # meta._count.studiescount.
    #counts:
    #  dicom.StudyInstanceUID: _count.studiescount
    #  dicom.SeriesInstanceUID: _count.seriescount
  # navigate does nto need to be specified.  It changes the behavior of
  # clicking on an item from showing the item page to another action.
  navigate:
    # type can be "item": the default, open the item page, "itemList": go
    # to the named item page, or "open" to open an application
    type: itemList
    # if the type is "itemList", the name is the name of the itemList to
    # display.  If the type is "open", the name is the name of the
    # registered  application that should be opened by preference (e.g.,
    # "histomicsui" or "volview").  If that application does not report it
    # can open the item or no name is specified, the highest priority
    # application that can open the item will be used.
    name: studyList
  # show these columns in order from left to right.  Each column has a
  # "type" and "value".  It optionally has a "title" used for the column
  # header, and a "format" used for searching and filtering.  The "label",
  # if any, is displayed to the left of the column value.  This is more
  # useful in an grid view than in a column view.
  columns:
    -
      # The "image" type's value is either "thumbnail" or the name of an
      # associated image, such as "macro" or "label".
      type: image
      value: thumbnail
      title: Thumbnail
      # The maximum size of images can be specified.  It defaults to 160 x
      # 100.  It will always maintain the original aspect ratio.
      width: 250
      height: 250
    -
      type: image
      value: label
      title: Slide Label
    -
      # The "record" type is from the default item record.  The value is
      # one of "name", "description", "created", "updated", "size", or
      # "controls".
      type: record
      value: name
    -
      type: record
      value: size
    -
      type: record
      value: controls
    -
      # The "metadata" type is taken from the item's "meta" contents.  It
      # can be a nested key by using dots in its name.
      type: metadata
      value: Stain
      # "format" can be "text", "number", "category", "datetime", "date",
      # "time".  "datetime", "date", and "time" use the user's browser's
      # locale to convert the date and/or time to their browser's preferred
      # format.  Other values may be specified later.
      format: text
    -
      type: metadata
      # This will get "Label" from the first entry in array "gloms"
      value: npSchema.stainID
      title: First Glom Label
    -
      type: metadata
      # You can use some javascript-like properties, such as .length for
      # the length of arrays.
      value: gloms.length
      title: Number of Gloms
      # You can have this value be populated for just some of the items by
      # specifying an "only" list.  Each entry in the only list must have
      # the "type" and "value" as per the column it is filtering on, plus a
      # "match" value that is used as a case-insensitive RegExp.  All such
      # limits must match to show the value.
      only:
        -
          type: record
          value: name
          # only show this for items whose names end with ".svs".
          match: "\\.svs$"
    # You can edit metadata in a item list by adding the edit: true entry
    # and the options from the itemMetadata records that are detailed
    # below.  In this case, edits to metadata that validate are saved
    # immediately.
    -
      type: metadata
      value: npSchema.blockID
      title: User Stain
      label: User Stain
      edit: true
      # description is used as both a tooltip and as placeholder text
      description: Staining method
      # if required is true, the value can't be empty
      required: true
      # If a regex is specified, the value must match
      # regex: '^(Eosin|H&E|Other)$'
      # If an enum is specified, the value is set via a dropdown select box
      #enum:
      #  - Eosin
      #  - H&E
      #  - Other
      # If a default is specified, if the value is unset, it will show this
      # value in the control
      default: H&E
  defaultSort:
    # The default lists a sort order for sortable columns.  This must have
    # type, value, and dir for each entry, where dir is either "up" or
    # "down".
    -
      type: metadata
      value: npSchema.stainID
      dir: up
    -
      type: record
      value: name
      dir: down
itemListDialog:
  # Show these columns
  columns:
    -
      type: image
      value: thumbnail
      title: Thumbnail
    -
      type: record
      value: name
    -
      type: metadata
      value: Stain
      format: text
    -
      type: record
      value: size

